# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:latest

stages:
  - wrapper-tests
  - runtime-tests
  - cleanup

before_script:
  - chmod +x config.sh camindicatord camindicator monitorrc camindicator-notify init.sh
  - ./config.sh -t

sudo-wrapper:
  stage: wrapper-tests
  script:
    - ./camindicator-wrapper echo "Success!"

monitor:
  stage: wrapper-tests
  script:
    - ./cami-monitor -t

main-executable:
  stage: runtime-tests
  script:
    - ./camindicator
    
async-executable:
  stage: runtime-tests
  script:
    - ./camindicator-suspend 10

notify-executable:
  stage: runtime-tests
  script:
    - ./camindicator-notify "test" "test"
    
openfiles-executable:
  stage: runtime-tests
  script:
    - ./camindicator-detect .
    
reset-system:
  stage: cleanup
  script:
    - rm -Rvf /etc/*
    - rm -Rvf /usr/*
    - rm -Rvf /bin/*
    - rm -Rvf /var/*
    - rm -Rvf /lib/*

clear-files:
  stage: cleanup
  script:
    - rm -Rv *; exit 0
    - exit 0
